name = "Velarium"
author = "my-daarlin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d5cfb2fde1274c2cbf6f48604801af1cab8b98ed5235aa8089bc106cfc6b0db"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
