name = "Starlight"
author = "my-daarlin"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98d24fae70fd92a1f84d8a57932507711c45785de11d5e00fc38245a33375fac"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
