enabled = true
anchor = "HOTBAR"
side = "LEFT"
offsetX = 0
offsetY = 0
style = "HOTBAR"
orientation = "HORIZONTAL"
widgetShown = "NOT_EMPTY"
offhandSlotBehavior = "ADHERE"
durabilityDisplay = "BAR"
pushBossbars = true
pushStatusEffectIcons = true
pushSubtitles = true
reversed = false
iconsShown = true
warningShown = true
playBreakSound = true
minDurabilityValue = 20
minDurabilityPercentage = 0.1
warningBobIntensity = 3
